#!/usr/bin/env php
<?php

use Swoole\Coroutine;

$context = Coroutine::getContext();
var_dump($context);

Coroutine::create(function(){
    $context = Coroutine::getContext();
    $context->hello = 1;
    var_dump($context);
    Coroutine::create(function(){
        $context = Coroutine::getContext();
        $context->world = 1;
        var_dump($context);
    });
});