#!/usr/bin/env php
<?php

// 自动加载
require_once dirname(__DIR__) . '/vendor/autoload.php';

// 引入对象
use Minimal\Application;

// 显示错误
ini_set('display_errors', 'stderr');
// 报告错误
error_reporting(E_ALL);

// 应用对象
$app = new Application(__DIR__);

// 执行应用
$app->execute();
