#!/usr/bin/env php
<?php

// 自动加载
require_once dirname(__DIR__) . '/vendor/autoload.php';
// 显示错误
ini_set('display_errors', 'stderr');
// 报告错误
error_reporting(E_ALL);
// 时区设置
date_default_timezone_set('Asia/Shanghai');

try {
    // printf('Memory: %sMB' . PHP_EOL, $before = round(memory_get_usage()/1024/1024, 2));

    // 应用实例
    $app = new Minimal\Application(__DIR__);

    // printf('Memory: %sMB, Framework: %sMB' . PHP_EOL, $after = round(memory_get_usage()/1024/1024, 2), $after - $before);
} catch (\Throwable $th) {
    echo 'Exception::' . $th->getMessage() . PHP_EOL;
    echo 'File::' . $th->getFile() . PHP_EOL;
    echo 'Line::' . $th->getLine() . PHP_EOL;
}
