#!/usr/bin/env php
<?php
// 自动加载
require_once dirname(__DIR__) . '/vendor/autoload.php';
// 显示错误
ini_set('display_errors', 'stderr');
// 报告错误
error_reporting(E_ALL);
// 时区设置
date_default_timezone_set('Asia/Shanghai');

try {

    $server = new Swoole\Http\Server('0.0.0.0', 8080);

    $server->on('Start', function($server){
        printf('OnStart:: MasterPid: %s, ManagerPid: %s' . PHP_EOL, $server->master_pid, $server->manager_pid);
    });

    $server->on('WorkerStart', function($server, $workerId){
        printf('OnWorkerStart:: WorkerId: %s' . PHP_EOL, $workerId);
        $configs = require __DIR__ . '/config/db.php';
        $configs['worker_num'] = $server->setting['worker_num'];
        $server->database = new Minimal\Database\Manager($configs, $workerId);
    });
    $server->on('request', function($req, $res) use($server){
        try {

            var_dump($server->database);
            $res->status(200);
            $res->header('Content-Type', 'application/json;charset=utf-8');
            $res->end(json_encode([
                $server->database->query('SELECT * FROM `brand` WHERE id = ?', [1]),
                $server->database->query('SELECT `id`, `name` FROM `brand` WHERE id = ?', [2]),
            ]));
        } catch (\Throwable $th) {
            echo $th->getMessage(), PHP_EOL;
            echo $th->getFile(), PHP_EOL;
            echo $th->getLine(), PHP_EOL;
            print_r($th->getTrace());
            echo PHP_EOL;
        }
    });
    $server->start();

} catch (\Throwable $th) {
    echo 'Exception::' . $th->getMessage() . PHP_EOL;
    echo 'File::' . $th->getFile() . PHP_EOL;
    echo 'Line::' . $th->getLine() . PHP_EOL;
}
